# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Аватар')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='Никнейм')),
                ('fullname', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус')),
                ('rank', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ранг')),
                ('role', models.CharField(blank=True, max_length=200, null=True, verbose_name='Роль')),
            ],
            options={
                'ordering': ('fullname',),
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
