# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_public',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата основания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mission',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Миссия проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на проект'),
        ),
    ]
