# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160811_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200, unique=True, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Тело')),
                ('pub_date', models.DateTimeField()),
                ('isNotification', models.BooleanField(default=False)),
                ('update_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='Автор новости')),
                ('update_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project', verbose_name='Проект')),
            ],
            options={
                'verbose_name_plural': 'Новости',
                'verbose_name': 'Новость',
                'ordering': ('heading',),
            },
        ),
    ]
