# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
