# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160811_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=200, verbose_name='Канал')),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('isArchived', models.BooleanField(default=False)),
                ('channel_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project', verbose_name='Проект')),
            ],
            options={
                'ordering': ('channel_name',),
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='ChannelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCreator', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_user',
            field=models.ManyToManyField(through='main.ChannelUser', to='main.User', verbose_name='Участники канала'),
        ),
    ]
