# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160811_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
