# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='Коммент')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='Автор комментария')),
                ('comment_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Update', verbose_name='Новость')),
            ],
            options={
                'ordering': ('comment',),
                'verbose_name_plural': 'Комментарии',
                'verbose_name': 'Коммент',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('like_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('like_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Update')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200, verbose_name='Оповещение')),
                ('notification_date', models.DateTimeField()),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
            options={
                'ordering': ('notification',),
                'verbose_name_plural': 'Оповещения',
                'verbose_name': 'Оповещение',
            },
        ),
        migrations.CreateModel(
            name='SubscribeProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
                ('subscribe_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
                ('subscribe_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Project')),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
